apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octopus-agent-data
  namespace: octopus-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: octopus-redis-data
  namespace: octopus-agent
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
