import type { SwarmAgent, SwarmSession, TraceEntry } from "./types";

export function buildMockSession(): SwarmSession {
  const agents: SwarmAgent[] = [
    {
      id: "a1",
      index: 1,
      name: "娄校长",
      role: "技术专家",
      motto: "谦逊而成信，聚力而事成",
      avatarEmoji: "🎩",
      hue: 28,
      skills: ["company-research", "docx", "skill-finder"],
      stats: { taskCount: 127, rating: 4.6 },
      personality: ["严谨", "爱引用论文"],
      task: '请研究 "harness" 作为技术/开发工具的相关信息',
      details: [
        "技术架构与核心能力",
        "CI/CD 流程与部署策略",
        "Kubernetes 原生支持程度",
        "与 Jenkins / GitLab CI 的对比",
      ],
      status: "done",
      progress: 1,
      tokenUsed: 18200,
      tokenBudget: 30000,
    },
    {
      id: "a2",
      index: 2,
      name: "赛文",
      role: "商业研究专家",
      motto: "数据为证，洞见为王",
      avatarEmoji: "🧑",
      hue: 210,
      skills: ["company-research", "competitive-landscape"],
      stats: { taskCount: 83, rating: 4.4 },
      personality: ["务实", "快嘴"],
      task: '请研究 Harness Inc. 这家公司的商业信息',
      details: [
        "公司背景：成立时间、创始人、总部位置",
        "融资历史：各轮融资规模、估值、投资方",
        "产品线：主要产品和解决方案",
        "商业模式：定价模式、目标客户",
        "市场地位：竞争对手、市场份额、行业认可",
      ],
      status: "iterating",
      progress: 0.62,
      tokenUsed: 22400,
      tokenBudget: 30000,
    },
    {
      id: "a3",
      index: 3,
      name: "朱迪",
      role: "学术研究专家",
      motto: "厚积薄发，字字珠玑",
      avatarEmoji: "👩",
      hue: 142,
      skills: ["people-research", "content-breakdown", "docx"],
      stats: { taskCount: 64, rating: 4.8 },
      personality: ["学究", "耐心"],
      task: '请研究 "harness" 相关的学术研究文献',
      details: [
        "近 5 年顶会论文",
        "与资源利用率 / 调度相关的研究",
        "引用量 Top 10 的关键文献",
      ],
      status: "analyzing",
      progress: 0.38,
      tokenUsed: 9800,
      tokenBudget: 30000,
    },
    {
      id: "a4",
      index: 4,
      name: "菲邵",
      role: "行业应用专家",
      motto: "纸上得来终觉浅",
      avatarEmoji: "🧔",
      hue: 330,
      skills: ["market-insight-product-selection", "content-strategy"],
      stats: { taskCount: 41, rating: 4.2 },
      personality: ["接地气"],
      task: '请研究 "harness" 在各行业的实际应用情况',
      details: [
        "金融、互联网、制造业典型案例",
        "落地 ROI 与踩坑记录",
      ],
      status: "done",
      progress: 1,
      tokenUsed: 14100,
      tokenBudget: 30000,
    },
  ];

  const now = Date.now();
  const trace: TraceEntry[] = [
    {
      id: "t1",
      agentId: "a1",
      timestamp: now - 120_000,
      kind: "think",
      title: "研究 Harness CI/CD 平台优势",
    },
    {
      id: "t2",
      agentId: "a1",
      timestamp: now - 110_000,
      kind: "search",
      title: "搜索网页: Harness CI/CD platform features architecture 2024",
      detail: "34 个结果",
    },
    {
      id: "t3",
      agentId: "a1",
      timestamp: now - 90_000,
      kind: "read",
      title: "Harness Developer Hub",
      detail:
        "This topic shows you how to deploy a publicly-available NGINX Docker image and manifest into your Kubernetes cluster using a rolling update strategy...",
      url: "https://developer.harness.io",
      faviconEmoji: "📘",
    },
    {
      id: "t4",
      agentId: "a1",
      timestamp: now - 70_000,
      kind: "read",
      title: "Implementing CI/CD for Microservices Architecture - Harness IO",
      detail:
        "Automating Continuous Integration with Continuous Deployment (CD) is the practice of automatically pushing changes to production...",
      url: "https://harness.io",
      faviconEmoji: "📗",
    },
    {
      id: "t5",
      agentId: "a1",
      timestamp: now - 40_000,
      kind: "write",
      title: "创建文件: harness_technical_report.md",
    },
    {
      id: "t6",
      agentId: "a2",
      timestamp: now - 30_000,
      kind: "search",
      title: "搜索网页: Harness Inc funding rounds valuation",
      detail: "12 个结果",
    },
    {
      id: "t7",
      agentId: "a3",
      timestamp: now - 20_000,
      kind: "read",
      title: "arXiv: Resource-aware Scheduling in Cloud Harness",
      url: "https://arxiv.org",
      faviconEmoji: "📕",
    },
  ];

  return {
    id: "session-1",
    title: "harness 研究",
    status: "running",
    mode: "replay",
    agents,
    trace,
    deliverables: [
      {
        name: "技术研究报告",
        path: "/mnt/okcomputer/output/harness_technical_report.md",
        ownerAgentIds: ["a1"],
      },
      {
        name: "企业研究报告",
        path: "/mnt/okcomputer/output/harness_inc_research_report.md",
        ownerAgentIds: ["a2"],
      },
      {
        name: "学术研究报告",
        path: "/mnt/okcomputer/output/harness_research_report.md",
        ownerAgentIds: ["a3"],
      },
      {
        name: "行业应用报告",
        path: "/mnt/okcomputer/output/harness_industry_application_report.md",
        ownerAgentIds: ["a4"],
      },
    ],
    handoffs: [
      {
        agentId: "a1",
        taskId: "technical",
        phaseIndex: 0,
        nodeIds: ["technical"],
        status: "completed",
        summary: "Technical research report completed with CI/CD architecture notes.",
        artifacts: ["/mnt/okcomputer/output/harness_technical_report.md"],
        costUsd: 0.03,
      },
      {
        agentId: "a2",
        taskId: "business",
        phaseIndex: 0,
        nodeIds: ["business"],
        status: "running",
        summary: "Business model and funding research is being consolidated.",
        artifacts: ["/mnt/okcomputer/output/harness_inc_research_report.md"],
        costUsd: 0.02,
      },
      {
        agentId: "a3",
        taskId: "academic",
        phaseIndex: 0,
        nodeIds: ["academic"],
        status: "running",
        summary: "Academic sources are being screened for scheduling relevance.",
        artifacts: [],
        costUsd: 0.01,
      },
      {
        agentId: "a4",
        taskId: "industry",
        phaseIndex: 0,
        nodeIds: ["industry"],
        status: "completed",
        summary: "Industry application examples were delivered.",
        artifacts: ["/mnt/okcomputer/output/harness_industry_application_report.md"],
        costUsd: 0.02,
      },
    ],
    phaseReports: [
      {
        phaseIndex: 0,
        nodeIds: ["technical", "business", "academic", "industry"],
        assignmentCount: 4,
        handoffCount: 4,
        succeeded: 2,
        failed: 0,
        status: "partial",
        wallMs: 120000,
        costUsd: 0.08,
      },
    ],
    workflow: {
      stage: "assigning_tasks",
      status: "running",
      progress: 0.5,
      totalTasks: 4,
      completedTasks: 2,
      failedTasks: 0,
      cancelledTasks: 0,
      updatedAt: Date.now(),
    },
    summary:
      "基于四位专家的并行研究，Harness 在 AI 集成、安全左移、云原生支持与成本优化四大方向上展现出领先优势。",
    sourcePrompt:
      "Analyze Harness Inc. from technical, business, academic, and industry angles. Produce a structured market research report with source-backed findings.",
  };
}
