"""Source for the isolated Python process that installs a Landlock ruleset.

Kept outside :mod:`sandbox` so the backend policy code does not also carry a
second executable program inline.  The wrapper remains a string because the
target interpreter may be a packaged runtime where ``python -m`` module
discovery is not available.
"""

from __future__ import annotations

LANDLOCK_WRAPPER = r"""
# Landlock confinement wrapper (generated by LandlockBackend).
#
# Applies a deny-by-default filesystem ruleset through the Landlock LSM
# syscalls (kernel >= 5.13), then execs the real command. Reads and
# execution of the whole tree stay allowed (language runtimes need them);
# writes are allowed only under the paths in OCTOPUS_LANDLOCK_SPEC, plus
# the /dev/null sink the shells require.

import ctypes
import json
import os
import sys

libc = ctypes.CDLL(None, use_errno=True)
SYS_LANDLOCK_CREATE_RULESET = 444
SYS_LANDLOCK_ADD_RULE = 445
SYS_LANDLOCK_RESTRICT_SELF = 446
LANDLOCK_RULE_PATH_BENEATH = 1
PR_SET_NO_NEW_PRIVS = 38

# linux/landlock.h access rights (ABI v1 bits; ABI v2 adds REFER,
# ABI v3 adds TRUNCATE - both handled below).
EXECUTE = 1 << 0
WRITE_FILE = 1 << 1
READ_FILE = 1 << 2
READ_DIR = 1 << 3
REMOVE_DIR = 1 << 4
REMOVE_FILE = 1 << 5
MAKE_CHAR = 1 << 6
MAKE_DIR = 1 << 7
MAKE_REG = 1 << 8
MAKE_SOCK = 1 << 9
MAKE_FIFO = 1 << 10
MAKE_BLOCK = 1 << 11
MAKE_SYM = 1 << 12
REFER = 1 << 13
TRUNCATE = 1 << 14

_READ = EXECUTE | READ_FILE | READ_DIR
_WRITE = (
    WRITE_FILE
    | REMOVE_DIR
    | REMOVE_FILE
    | MAKE_CHAR
    | MAKE_DIR
    | MAKE_REG
    | MAKE_SOCK
    | MAKE_FIFO
    | MAKE_BLOCK
    | MAKE_SYM
    | REFER
    | TRUNCATE
)


class _Attr(ctypes.Structure):
    _fields_ = [("handled_access_fs", ctypes.c_uint64)]


class _RuleBeneath(ctypes.Structure):
    _fields_ = [("allowed_access", ctypes.c_uint64), ("parent_fd", ctypes.c_int)]


attr = _Attr(_READ | _WRITE)
ruleset_fd = libc.syscall(
    SYS_LANDLOCK_CREATE_RULESET, ctypes.byref(attr), ctypes.sizeof(attr), 0
)
if ruleset_fd < 0:
    raise OSError(ctypes.get_errno(), "landlock_create_ruleset")


def add_path_beneath(path, allowed):
    try:
        parent_fd = os.open(path, os.O_PATH)
    except OSError:
        return  # path absent at confine time; not a failure
    try:
        rule = _RuleBeneath(allowed, parent_fd)
        rc = libc.syscall(
            SYS_LANDLOCK_ADD_RULE,
            ruleset_fd,
            LANDLOCK_RULE_PATH_BENEATH,
            ctypes.byref(rule),
            0,
        )
        if rc != 0:
            raise OSError(ctypes.get_errno(), "landlock_add_rule(" + path + ")")
    finally:
        os.close(parent_fd)


add_path_beneath("/", _READ)
add_path_beneath("/dev/null", WRITE_FILE | TRUNCATE)
for path in json.loads(os.environ["OCTOPUS_LANDLOCK_SPEC"])["write_paths"]:
    add_path_beneath(path, _READ | _WRITE)

# Unprivileged processes must set no_new_privs before restricting themselves.
# Without this, Landlock always fails with EPERM in the non-root production
# container even when the host kernel supports the ABI.
rc = libc.prctl(PR_SET_NO_NEW_PRIVS, 1, 0, 0, 0)
if rc != 0:
    raise OSError(ctypes.get_errno(), "prctl(PR_SET_NO_NEW_PRIVS)")

rc = libc.syscall(SYS_LANDLOCK_RESTRICT_SELF, ruleset_fd, 0)
if rc != 0:
    raise OSError(ctypes.get_errno(), "landlock_restrict_self")

if "--" in sys.argv:
    argv = sys.argv[sys.argv.index("--") + 1 :]
else:
    argv = sys.argv[1:]
os.execvpe(argv[0], argv, os.environ)
"""

__all__ = ["LANDLOCK_WRAPPER"]
