"""One-click local SearXNG for the private web-search backend.

octopus-agent already speaks SearXNG (``runtime.execution.suckers.web_skills``:
``WEB_SEARCH_BACKEND=searxng`` + ``SEARXNG_URL``). What was missing is a way to
*get* a local SearXNG without the user hand-running ``docker run``. This module
deploys + supervises one as a Docker container — the same lifecycle pattern as
the octopus-storage supervisor, but the child is a container, not a process.

Footprint: this adds **no Python dependency** (just ``httpx``, already core, and
the ``docker`` CLI). The ~200–300 MB image lives in Docker, never in our package.

Best-effort + graceful at every step: no Docker / daemon down / pull fails →
log + report; the agent runs fine and web search falls back to the default
``ddg`` backend (zero config). The container binds **127.0.0.1 only** and the
generated settings carry a random secret — nothing here is an injection surface
(all docker calls are shell-free argv lists with no user-interpolated values).
"""

from __future__ import annotations

import contextlib
import logging
import os
import secrets
import shutil
import subprocess
import threading
import time
from pathlib import Path
from typing import Any

_LOG = logging.getLogger("octopus.searxng_supervisor")
_lock = threading.Lock()

_DEFAULT_PORT = "8888"
_DEFAULT_IMAGE = "searxng/searxng:2026.5.31-7159b8aed"  # pinned; override via env
_DEFAULT_CONTAINER = "octopus-searxng"

_HEARTBEAT_INTERVAL_S = 20.0
_RESTART_BACKOFF_S = 30.0

# ``_managed`` is True once we own a local container's lifecycle — set by an
# explicit enable() or by autostart. The heartbeat only (re)starts when managed,
# so an externally-run SearXNG is observed but never touched.
_managed = False
_heartbeat_started = False

_status_lock = threading.Lock()
_state: dict[str, Any] = {
    "up": False,
    "last_check_ts": 0.0,
    "restart_count": 0,
    "last_restart_ts": 0.0,
    "heartbeat": False,
}


# ── config (all pure / unit-testable) ────────────────────────────────────────
def _autostart_enabled() -> bool:
    return os.environ.get("OCTOPUS_SEARXNG_AUTOSTART", "").strip().lower() in (
        "1",
        "true",
        "yes",
        "on",
    )


def _searxng_port() -> str:
    return (os.environ.get("OCTOPUS_SEARXNG_PORT") or "").strip() or _DEFAULT_PORT


def _image() -> str:
    return (os.environ.get("OCTOPUS_SEARXNG_IMAGE") or "").strip() or _DEFAULT_IMAGE


def _container_name() -> str:
    return (os.environ.get("OCTOPUS_SEARXNG_CONTAINER") or "").strip() or _DEFAULT_CONTAINER


def _local_url() -> str:
    return f"http://127.0.0.1:{_searxng_port()}"


def _settings_dir() -> Path:
    return Path.home() / ".octopus" / "searxng"


def _render_settings(secret: str) -> str:
    """Minimal settings.yml: keep image defaults, but enable the JSON API (the
    agent reads JSON, not HTML) and disable the bot limiter (it blocks
    programmatic requests). Carries a baked random ``secret_key`` so the image
    never has to mutate a read-only mount."""
    return (
        "# Generated by octopus-agent searxng supervisor. Safe to delete; a fresh\n"
        "# secret is regenerated on next enable.\n"
        "use_default_settings: true\n"
        "server:\n"
        f'  secret_key: "{secret}"\n'
        "  limiter: false\n"
        "  image_proxy: true\n"
        "search:\n"
        "  formats:\n"
        "    - html\n"
        "    - json\n"
    )


def _run_argv(*, docker: str, name: str, port: str, settings_file: str, image: str) -> list[str]:
    """The ``docker run`` argv. Binds 127.0.0.1 only (never 0.0.0.0) and mounts
    just settings.yml read-only, so the image keeps its own uwsgi.ini and no
    host-dir ownership dance is needed."""
    return [
        docker,
        "run",
        "-d",
        "--name",
        name,
        "--restart",
        "unless-stopped",
        "-p",
        f"127.0.0.1:{port}:8080",
        "-v",
        f"{settings_file}:/etc/searxng/settings.yml:ro",
        image,
    ]


def _should_restart(
    *,
    up: bool,
    managed: bool,
    container_running: bool,
    docker_present: bool,
    now: float,
    last_restart: float,
    backoff_s: float,
) -> bool:
    """Pure restart decision (testable, thrash-free): relaunch only when the
    service is DOWN, we own its lifecycle, Docker exists, the container isn't
    already (re)booting, and we're past the backoff window."""
    if up or not managed or not docker_present or container_running:
        return False
    return (now - last_restart) >= backoff_s


# ── docker / liveness (need Docker; not unit-tested) ─────────────────────────
def _docker() -> str | None:
    return shutil.which("docker")


def _docker_running(docker: str) -> bool:
    try:
        r = subprocess.run(  # noqa: S603 — resolved path, argv list, shell=False
            [docker, "info", "--format", "{{.ServerVersion}}"],
            capture_output=True,
            timeout=8,
        )
        return r.returncode == 0
    except Exception:  # noqa: BLE001
        return False


def _container_exists(docker: str, name: str) -> bool:
    try:
        r = subprocess.run(  # noqa: S603
            [docker, "ps", "-aq", "-f", f"name=^{name}$"],
            capture_output=True,
            text=True,
            timeout=8,
        )
        return r.returncode == 0 and bool(r.stdout.strip())
    except Exception:  # noqa: BLE001
        return False


def _container_running(docker: str, name: str) -> bool:
    try:
        r = subprocess.run(  # noqa: S603
            [docker, "inspect", "-f", "{{.State.Running}}", name],
            capture_output=True,
            text=True,
            timeout=8,
        )
        return r.returncode == 0 and r.stdout.strip() == "true"
    except Exception:  # noqa: BLE001
        return False


def _already_up(timeout: float = 1.5) -> bool:
    """Liveness of OUR local container, not auth: any HTTP response (incl. 4xx)
    counts as up; only a connection failure / timeout is down."""
    try:
        import httpx
    except Exception:  # noqa: BLE001
        return False
    try:
        with httpx.Client(timeout=timeout) as client:
            client.get(_local_url() + "/")
        return True
    except Exception:  # noqa: BLE001
        return False


def _ensure_settings() -> Path:
    d = _settings_dir()
    d.mkdir(parents=True, exist_ok=True)
    f = d / "settings.yml"
    if not f.exists():
        f.write_text(_render_settings(secrets.token_hex(32)), encoding="utf-8")
        with contextlib.suppress(OSError):
            f.chmod(0o644)
    return f


def _set_url_env(*, force: bool) -> None:
    """Point the web-search backend at our local container. ``force`` (explicit
    enable) overrides any existing value; otherwise we only fill an empty one so
    a user's external ``SEARXNG_URL`` is respected."""
    local = _local_url()
    if force or not os.environ.get("SEARXNG_URL", "").strip():
        os.environ["SEARXNG_URL"] = local


def _launch() -> bool:
    """Ensure the container is running: start an existing one, else ``docker run``
    (which pulls the image on first use — hence the generous timeout). Shell-free.
    Returns True on success."""
    docker = _docker()
    if not docker:
        return False
    name = _container_name()
    with _lock:
        if _container_running(docker, name):
            return True
        if _container_exists(docker, name):
            try:
                r = subprocess.run(  # noqa: S603
                    [docker, "start", name], capture_output=True, timeout=30
                )
            except Exception as exc:  # noqa: BLE001
                _LOG.warning("octopus-searxng start failed: %s", exc)
                return False
            if r.returncode == 0:
                _LOG.info("octopus-searxng container started")
                return True
            return False
        settings = _ensure_settings()
        argv = _run_argv(
            docker=docker,
            name=name,
            port=_searxng_port(),
            settings_file=str(settings),
            image=_image(),
        )
        try:
            r = subprocess.run(argv, capture_output=True, timeout=600)  # noqa: S603 — may pull
        except Exception as exc:  # noqa: BLE001
            _LOG.warning("octopus-searxng run failed: %s", exc)
            return False
        if r.returncode == 0:
            _LOG.info("octopus-searxng deployed: %s", " ".join(argv))
            return True
        _LOG.warning(
            "octopus-searxng run exited %s: %s",
            r.returncode,
            (r.stderr or b"").decode(errors="replace")[:300],
        )
        return False


def _wait_ready(*, attempts: int = 60, interval: float = 1.0) -> None:
    for _ in range(attempts):
        if _already_up():
            _record(True)
            _LOG.info("octopus-searxng ready at %s", _local_url())
            return
        time.sleep(interval)
    _LOG.info("octopus-searxng not ready yet; web search will pick it up once it is")


def _record(up: bool) -> None:
    with _status_lock:
        _state["up"] = up
        _state["last_check_ts"] = time.time()


# ── public API ───────────────────────────────────────────────────────────────
def searxng_status() -> dict[str, Any]:
    """Snapshot for a status endpoint / UI light. Heartbeat-cached when running,
    else probes once. ``docker_present`` is a cheap PATH check (no daemon call)."""
    with _status_lock:
        snap = dict(_state)
    if not snap["heartbeat"]:
        snap["up"] = _already_up()
        snap["last_check_ts"] = time.time()
    snap["docker_present"] = _docker() is not None
    snap["managed"] = _managed
    snap["autostart"] = _autostart_enabled()
    snap["container"] = _container_name()
    snap["port"] = _searxng_port()
    snap["url"] = _local_url()
    return snap


def _enable_worker() -> None:
    try:
        if _launch():
            _set_url_env(force=True)
            _wait_ready()
    except Exception as exc:  # noqa: BLE001
        _LOG.warning("octopus-searxng enable worker failed: %s", exc)


def enable_searxng() -> dict[str, Any]:
    """One-click deploy of a local SearXNG. Returns immediately with a status
    (``docker_missing`` / ``docker_not_running`` / ``already_running`` /
    ``starting``) — the image pull + boot run in the background; poll
    ``searxng_status()`` for ``up``. Never raises."""
    global _managed
    docker = _docker()
    if not docker:
        return {**searxng_status(), "status": "docker_missing"}
    if not _docker_running(docker):
        return {**searxng_status(), "status": "docker_not_running"}
    _managed = True
    try:
        if _already_up():
            _set_url_env(force=True)
            _record(True)
            start_searxng_heartbeat()
            return {**searxng_status(), "status": "already_running"}
        threading.Thread(target=_enable_worker, name="searxng-enable", daemon=True).start()
        start_searxng_heartbeat()
        return {**searxng_status(), "status": "starting"}
    except Exception as exc:  # noqa: BLE001
        _LOG.warning("octopus-searxng enable failed: %s", exc)
        return {**searxng_status(), "status": "error", "error": str(exc)}


def disable_searxng() -> dict[str, Any]:
    """Stop the managed container (kept, not removed, so re-enable is instant)
    and release ``SEARXNG_URL`` if we set it (never clobbers an external one)."""
    global _managed
    _managed = False
    docker = _docker()
    if docker:
        with contextlib.suppress(Exception):
            subprocess.run(  # noqa: S603
                [docker, "stop", _container_name()], capture_output=True, timeout=30
            )
    if os.environ.get("SEARXNG_URL", "").strip() == _local_url():
        os.environ.pop("SEARXNG_URL", None)
    _record(False)
    return {**searxng_status(), "status": "stopped"}


def maybe_start_searxng() -> str:
    """Boot-time autostart (opt-in via ``OCTOPUS_SEARXNG_AUTOSTART``). Conservative:
    if ``SEARXNG_URL`` is already set (external instance), defers to it. Returns
    ``disabled`` / ``external_configured`` / ``docker_missing`` /
    ``docker_not_running`` / ``already_running`` / ``started`` / ``error``."""
    global _managed
    if not _autostart_enabled():
        return "disabled"
    if os.environ.get("SEARXNG_URL", "").strip():
        return "external_configured"
    docker = _docker()
    if not docker:
        return "docker_missing"
    try:
        if _already_up():
            _set_url_env(force=True)
            _record(True)
            _managed = True
            start_searxng_heartbeat()
            return "already_running"
        if not _docker_running(docker):
            return "docker_not_running"
        _managed = True
        threading.Thread(target=_enable_worker, name="searxng-autostart", daemon=True).start()
        start_searxng_heartbeat()
        return "started"
    except Exception as exc:  # noqa: BLE001
        _LOG.warning("octopus-searxng autostart failed: %s", exc)
        return "error"


def start_searxng_heartbeat() -> None:
    """Start the supervision heartbeat once (idempotent, daemon thread). No-op
    unless we manage a local container — an external SearXNG is observed via
    status() but never restarted by us."""
    global _heartbeat_started
    if not _managed:
        return
    with _status_lock:
        if _heartbeat_started:
            return
        _heartbeat_started = True
        _state["heartbeat"] = True
    threading.Thread(target=_heartbeat_loop, name="searxng-heartbeat", daemon=True).start()
    _LOG.info("octopus-searxng heartbeat supervisor started")


def _heartbeat_loop() -> None:
    while True:
        time.sleep(_HEARTBEAT_INTERVAL_S)
        try:
            up = _already_up()
            _record(up)
            if up or not _managed:
                continue
            docker = _docker()
            if not docker:
                continue
            running = _container_running(docker, _container_name())
            with _status_lock:
                last_restart = float(_state["last_restart_ts"])
            should = _should_restart(
                up=up,
                managed=_managed,
                container_running=running,
                docker_present=True,
                now=time.time(),
                last_restart=last_restart,
                backoff_s=_RESTART_BACKOFF_S,
            )
            if should and _launch():
                _set_url_env(force=False)
                with _status_lock:
                    _state["restart_count"] = int(_state["restart_count"]) + 1
                    _state["last_restart_ts"] = time.time()
                _LOG.warning("searxng heartbeat: was down — relaunched")
        except Exception as exc:  # noqa: BLE001 — the heartbeat must never die
            _LOG.debug("searxng heartbeat tick error: %s", exc)
